package abcbankpack.view;

import abcbankpack.model.Customers;
import abcbankpack.model.MyIconImage;
import abcbankpack.model.Transaction;
import javax.swing.JOptionPane;

/**
 *
 * @author Miracle Okafor
 */
public class EntryForm extends javax.swing.JFrame {

    /**
     * Creates new form EntryForm
     */
    public EntryForm() {
        initComponents();
        MyIconImage mic = new MyIconImage();
        setIconImage(mic.getIconImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        surnameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        genderField = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        homeField = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        balanceField = new javax.swing.JTextField();
        officerField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        regBtn = new javax.swing.JButton();
        regResetBtn = new javax.swing.JButton();
        successLabel = new javax.swing.JLabel();
        failedLabel = new javax.swing.JLabel();
        failedOpeningBalLabel = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tAcctNoField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tTransType = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        tAmtField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAmtInWordTextArea = new javax.swing.JTextArea();
        tSubBtn = new javax.swing.JButton();
        tSubClearBtn = new javax.swing.JButton();
        tab2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        acctNoField = new javax.swing.JTextField();
        checkBtn = new javax.swing.JButton();
        checkClearBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        acctNoLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        balLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entry Form");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abcbankpack/imgFol/zoneTech2.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tab1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel2.setText("Name");

        nameField.setBackground(new java.awt.Color(204, 204, 0));
        nameField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel3.setText("Surname");

        surnameField.setBackground(new java.awt.Color(204, 204, 0));
        surnameField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel4.setText("Gender");

        genderField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        genderField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel5.setText("Home Address");

        homeField.setBackground(new java.awt.Color(204, 204, 0));
        homeField.setColumns(20);
        homeField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        homeField.setRows(5);
        jScrollPane1.setViewportView(homeField);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel6.setText("Phone Number");

        phoneField.setBackground(new java.awt.Color(204, 204, 0));
        phoneField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel7.setText("Opening Balance");

        balanceField.setBackground(new java.awt.Color(204, 204, 0));
        balanceField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        officerField.setBackground(new java.awt.Color(204, 204, 0));
        officerField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel8.setText("Account Officer");

        regBtn.setBackground(new java.awt.Color(0, 51, 255));
        regBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regBtn.setForeground(new java.awt.Color(255, 255, 255));
        regBtn.setText("Register");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        regResetBtn.setBackground(new java.awt.Color(0, 51, 255));
        regResetBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        regResetBtn.setText("Reset");
        regResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regResetBtnActionPerformed(evt);
            }
        });

        successLabel.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        successLabel.setForeground(new java.awt.Color(0, 153, 0));
        successLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        failedLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        failedLabel.setForeground(new java.awt.Color(255, 0, 0));
        failedLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        failedOpeningBalLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        failedOpeningBalLabel.setForeground(new java.awt.Color(255, 0, 0));
        failedOpeningBalLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab1Layout.createSequentialGroup()
                                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tab1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(failedOpeningBalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(surnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                        .addComponent(genderField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1)
                                        .addComponent(phoneField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                        .addComponent(balanceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                        .addComponent(officerField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                        .addGroup(tab1Layout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(regResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)))))
                            .addGroup(tab1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(failedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(failedOpeningBalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(officerField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(failedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regResetBtn)
                    .addComponent(regBtn))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Register Customer", new javax.swing.ImageIcon(getClass().getResource("/abcbankpack/imgFol/disk.png")), tab1); // NOI18N

        tab3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel14.setText("Account Number");

        tAcctNoField.setBackground(new java.awt.Color(204, 204, 0));
        tAcctNoField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel15.setText("Transaction Type");

        tTransType.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        tTransType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Withdrawals", "Deposit" }));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel16.setText("Amount");

        tAmtField.setBackground(new java.awt.Color(204, 204, 0));
        tAmtField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel17.setText("Amount in Words");

        tAmtInWordTextArea.setBackground(new java.awt.Color(204, 204, 0));
        tAmtInWordTextArea.setColumns(20);
        tAmtInWordTextArea.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        tAmtInWordTextArea.setRows(5);
        jScrollPane2.setViewportView(tAmtInWordTextArea);

        tSubBtn.setBackground(new java.awt.Color(0, 51, 255));
        tSubBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tSubBtn.setForeground(new java.awt.Color(255, 255, 255));
        tSubBtn.setText("Submit");
        tSubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSubBtnActionPerformed(evt);
            }
        });

        tSubClearBtn.setBackground(new java.awt.Color(0, 51, 255));
        tSubClearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tSubClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        tSubClearBtn.setText("Clear");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17))
                        .addGap(70, 70, 70)
                        .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tAcctNoField)
                            .addComponent(tTransType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tAmtField)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))
                    .addGroup(tab3Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(tSubBtn)
                        .addGap(18, 18, 18)
                        .addComponent(tSubClearBtn)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tAcctNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tTransType, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tAmtField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tSubBtn)
                    .addComponent(tSubClearBtn))
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaction", new javax.swing.ImageIcon(getClass().getResource("/abcbankpack/imgFol/card_front.png")), tab3); // NOI18N

        tab2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel9.setText("Account Number");

        acctNoField.setBackground(new java.awt.Color(204, 204, 0));
        acctNoField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N

        checkBtn.setBackground(new java.awt.Color(0, 51, 255));
        checkBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkBtn.setText("Check");
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });

        checkClearBtn.setBackground(new java.awt.Color(0, 51, 255));
        checkClearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkClearBtn.setText("Clear");
        checkClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkClearBtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel10.setText("Account Number");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel11.setText("Name");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel12.setText("Surname");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel13.setText("Balance");

        acctNoLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        acctNoLabel.setText("account number");

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        nameLabel.setText("name");

        surnameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        surnameLabel.setText("surname");

        balLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        balLabel.setText("balance");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(checkBtn)
                        .addGap(18, 18, 18)
                        .addComponent(checkClearBtn))
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(39, 39, 39)
                        .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(acctNoField, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(acctNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(surnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(balLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(acctNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBtn)
                    .addComponent(checkClearBtn))
                .addGap(135, 135, 135)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(acctNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(surnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(balLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Check Account Balance", new javax.swing.ImageIcon(getClass().getResource("/abcbankpack/imgFol/CARD TYPE.png")), tab2); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regResetBtnActionPerformed
        // TODO add your handling code here:
        resetAll();
        successLabel.setText("");
    }//GEN-LAST:event_regResetBtnActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        // TODO add your handling code here:
        if(nameField.getText().equals("") || surnameField.getText().equals("") || homeField.getText().equals("") 
                || phoneField.getText().equals("") || balanceField.getText().equals("") || officerField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter all field", "Whenever", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!balanceField.getText().matches("\\d+")){
            //JOptionPane.showMessageDialog(null, "Balance Must be Digit", "Invalid", JOptionPane.INFORMATION_MESSAGE);
            successLabel.setText("");
            failedOpeningBalLabel.setText("Balance Must be Digit");
            failedLabel.setText("Something Went Wrong");
        }
        else{
            Customers customer = new Customers();
            String selectedItem = (String)genderField.getSelectedItem();
            double newBal = Double.parseDouble(balanceField.getText());
            
            boolean register = customer.isRegister(nameField.getText(), surnameField.getText(), selectedItem, homeField.getText(), phoneField.getText(), newBal, officerField.getText());
            
            if(register){
                successLabel.setText("Registration was Successfull!!!");
                resetAll();
                
                //JOptionPane.showMessageDialog(null, "Registration was Successfull!!!", "Fine", JOptionPane.INFORMATION_MESSAGE);
       
            }
            else{
                successLabel.setText("");
                failedLabel.setText("Something Went Wrong");
                //JOptionPane.showMessageDialog(null, "Something Went Wrong", "Failed", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_regBtnActionPerformed

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        // TODO add your handling code here:
        if(acctNoField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter an account Number. ");
        }
        else if(!acctNoField.getText().matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Account Number must be in digit");
        }
        else if(acctNoField.getText().length() != 10){
            JOptionPane.showMessageDialog(this, "Invalid Account Number");
        }
        else{
            int acctNo = Integer.parseInt(acctNoField.getText());
            Customers customer = new Customers();
            customer.checkAccountBal(acctNo);
            
            acctNoLabel.setText(String.valueOf(acctNo));
            nameLabel.setText(customer.getName());
            surnameLabel.setText(customer.getSurname());
            balLabel.setText(String.format("$%,.2f",customer.getBalance()));
        }
    }//GEN-LAST:event_checkBtnActionPerformed

    private void tSubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSubBtnActionPerformed
        // TODO add your handling code here:
        if(tAcctNoField.getText().isEmpty() || tAmtField.getText().isEmpty() || tAmtInWordTextArea.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter all field","WhenEver",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!tAcctNoField.getText().matches("\\d+") || !tAmtField.getText().matches("\\d+")){
          JOptionPane.showMessageDialog(this, "Account Number or Amount must be Digit");   
        }
        else if(tAcctNoField.getText().length() != 10){
            JOptionPane.showMessageDialog(this, "Invalid Account number");
        }
        else{
            Transaction transaction = new Transaction();
            
            int transAccountNo = Integer.parseInt(tAcctNoField.getText());
            double transAmt = Double.parseDouble(tAmtField.getText());
            String selectedItem = (String)tTransType.getSelectedItem();
            
            boolean isTrans = transaction.doTransaction(transAccountNo, selectedItem, transAmt, tAmtInWordTextArea.getText());
            
            if(isTrans){
               JOptionPane.showMessageDialog(this, "Transaction was successfull!!!","Fine",JOptionPane.INFORMATION_MESSAGE);  
               tAcctNoField.setText("");
               tAmtField.setText("");
               tAmtInWordTextArea.setText("");
               
            }
            else{
                JOptionPane.showMessageDialog(this, "Something Went Wrong","Failed",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tSubBtnActionPerformed

    private void checkClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkClearBtnActionPerformed
        // TODO add your handling code here:
            acctNoField.setText("");
            acctNoLabel.setText("account Number");
            nameLabel.setText("name");
            surnameLabel.setText("surname");
            balLabel.setText("balance");
    }//GEN-LAST:event_checkClearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EntryForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acctNoField;
    private javax.swing.JLabel acctNoLabel;
    private javax.swing.JLabel balLabel;
    private javax.swing.JTextField balanceField;
    private javax.swing.JButton checkBtn;
    private javax.swing.JButton checkClearBtn;
    private javax.swing.JLabel failedLabel;
    private javax.swing.JLabel failedOpeningBalLabel;
    private javax.swing.JComboBox genderField;
    private javax.swing.JTextArea homeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField officerField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton regBtn;
    private javax.swing.JButton regResetBtn;
    private javax.swing.JLabel successLabel;
    private javax.swing.JTextField surnameField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField tAcctNoField;
    private javax.swing.JTextField tAmtField;
    private javax.swing.JTextArea tAmtInWordTextArea;
    private javax.swing.JButton tSubBtn;
    private javax.swing.JButton tSubClearBtn;
    private javax.swing.JComboBox tTransType;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    // End of variables declaration//GEN-END:variables

public void resetAll(){
        failedOpeningBalLabel.setText("");
        failedLabel.setText("");
        nameField.setText("");
        surnameField.setText("");
        homeField.setText("");
        phoneField.setText("");
        balanceField.setText("");
        officerField.setText("");
        tTransType.setSelectedIndex(0);
        
}

        
      
}
